apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lkoller-app-of-apps-3
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: lkoller
    name: in-cluster
  project: default
  source:
    path: app-of-apps-applications/app3
    repoURL: https://github.com/LukasKoller/argocd-training-examples.git
    targetRevision: HEAD
